### ISSUE TITLE
Use RocksDB or CockroachDB as store

### ISSUE THREAD

**Issue by pyros2097** [lunny/nodb#2]
Is there an easy way to change its backend datastore to use rocksdb or cockroachdb? Then we can have a distributed and scalable, fault tolerant nodb.
 
Or is it possible to implement it directly over cockroachdb as a layer above its storage?

**Comment by lunny** [comment]
Yes. Visit [https://github.com/lunny/nodb/tree/master/store](https://github.com/lunny/nodb/tree/master/store). It's easy to add rocksdb or cockroachdb to nodb backend. Nodb is designed as a file nosql library, if you want a distributed system, you can take a look at [ledisdb](http://ledisdb.com).
